### ISSUE TITLE
Issue when using "config.entity" apparently in combination with restriction-card.

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-card-mod#25]
My Home Assistant version: 0.105.2

My lovelace configuration method (GUI or yaml): YAML

What I am doing: Trying to change icon color based on entity state

What I expected to happen: The icon to change color

What happened instead: Got error in the logs and the color doesn't change (this was working before 0.105.x release

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
          - type: entities
            show_header_toggle: false
            entities:
              - type: "custom:restriction-card"
                row: true
                card:
                  type: entities
                  name: UK Powerstrip
                  entity: switch.studio_andrea_uk_powerstrip
                  tap_action:
                    action: none
                style: |
                  :host {
                    --paper-item-icon-color:
                      {% if is_state(config.entity, 'on') %}
                        rgb(251, 205, 65);
                      {% elif is_state(config.entity, 'off') %}
                        rgb(2550, 0, 0);
                      {% else %}
                        rgb(128, 128, 128);
                      {% endif %}
                  }

# End of code
```

Error messages from the browser console:
None in the console, this is from HA logs:
```
2020-02-07 12:48:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139907224751376] Error handling message: Unknown error
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 983, in wrapper
    return func(hass, *args[1:], **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 646, in is_state
    state_obj = _get_state(hass, entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 470, in _get_state
    state = hass.states.get(entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 876, in get
    return self._states.get(entity_id.lower())
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'entity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 254, in handle_render_template
    state_listener()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 242, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 223, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'dict object' has no attribute 'entity'
2020-02-07 12:48:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139907224751376] Error handling message: Unknown error
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 983, in wrapper
    return func(hass, *args[1:], **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 646, in is_state
    state_obj = _get_state(hass, entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 470, in _get_state
    state = hass.states.get(entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 876, in get
    return self._states.get(entity_id.lower())
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'entity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 254, in handle_render_template
    state_listener()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 242, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 223, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'dict object' has no attribute 'entity'
2020-02-07 12:48:08 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.139907224751376] Error handling message: Unknown error
Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 221, in async_render
    return compiled.render(kwargs).strip()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 3, in top-level template code
  File "/home/ha/homeassistant/lib/python3.7/site-packages/jinja2/sandbox.py", line 440, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 983, in wrapper
    return func(hass, *args[1:], **kwargs)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 646, in is_state
    state_obj = _get_state(hass, entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 470, in _get_state
    state = hass.states.get(entity_id)
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 876, in get
    return self._states.get(entity_id.lower())
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'entity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 254, in handle_render_template
    state_listener()
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 242, in state_listener
    msg["id"], {"result": template.async_render(variables)}
  File "/home/ha/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 223, in async_render
    raise TemplateError(err)
homeassistant.exceptions.TemplateError: UndefinedError: 'dict object' has no attribute 'entity'
```

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by SeLLeRoNe** [comment]
Please note, if I change config.entity with the actual entity it does work:

```          - type: entities
            show_header_toggle: false
            entities:
              - type: "custom:restriction-card"
                row: true
                card:
                  type: entities
                  name: UK Powerstrip
                  entity: switch.studio_andrea_uk_powerstrip
                  state_color: true
                  tap_action:
                    action: none
                style: |
                  :host {
                    --paper-item-icon-color:
                      {% if is_state('switch.studio_andrea_uk_powerstrip', 'on') %}
                        rgb(251, 205, 65);
                      {% elif is_state('switch.studio_andrea_uk_powerstrip', 'off') %}
                        rgb(2550, 0, 0);
                      {% else %}
                        rgb(128, 128, 128);
                      {% endif %}
                  }
```

**Comment by jcwillox** [comment]
The error you are getting is because the `entity` attribute doesn't exist inside the `config` object. If you look closely at the context for the `style` you'll see its inline with type, row, card..., this means the config it is returning is the one for your restriction card. If you wanted to access that `entity` you would need to do `config.card.entity`, but in doing this the card will no longer update automatically. 

The better option as you have done is just to explicitly state the entity_id.

**Comment by SeLLeRoNe** [comment]
Thanks for you reply, the only thing that doesn't really convince me is that it was working before the update without any changes in the configuration.

It might be that during the tests to debug this I missaaligned the stype to be on the restriction-card instead of the entities card, but even if I allign it to the entities card, the problem persist.

I think it might be more related to the introduction of state_color rather then anything else

**Comment by thomasloven** [comment]
@jcwillox is right, though. I don't see how this ever worked. 🤷

**Comment by SeLLeRoNe** [comment]
Go figure :D
Well I guess I'll stick with the entity name :)

Thanks
