### ISSUE TITLE
If variable in theme yaml breaks card style

### ISSUE THREAD

**Issue by bymem** [thomasloven/lovelace-card-mod#257]
Hi.

When adding a if statement in you'r theme yaml, it breaks the the styling that is already added in the cards style.
Example i have this in my card style: 

```
type: custom:stack-in-card
card_mod:
  style: |
    ha-card {
      padding: 12px !important;
      border-radius: 0px 0px 20px 20px !important;
      background-color: var(--card-background-color);
      margin: -29px -16px 16px -16px !important;
    }
```

Which give this results
<img width="545" alt="Screenshot 2023-02-27 at 12 55 22" src="https://user-images.githubusercontent.com/1265623/221557676-048872b7-23b2-4f90-9fb4-c5ddb898de64.png">

But when i added this line into the them yaml
```
card-mod-card: |
    ha-card {
      {% if config.entity.startswith('light.') and is_state(config.entity, 'on') %}
        background-color: red;
      {% endif %}
    }
```

It breaks card styling and results in this result.
<img width="528" alt="Screenshot 2023-02-27 at 12 55 56" src="https://user-images.githubusercontent.com/1265623/221557821-bce7a533-f7ac-4e1b-9345-454dc84ee043.png">

**Comment by ildar170975** [comment]
You are using `stack-in-card` and trying to use `config.entity` - what do you expect then?))

**Comment by bymem** [comment]
> You are using `stack-in-card` and trying to use `config.entity` - what do you expect then?))

Well i would expect it doesn't break the other styling not added to cards, where there is no lighting entities in.

the stack-in-card had no light entities in it, and "shouldn't" be effected by this styling from the theme.
The if statement styling does work, and turn every light entity red when they are turned on.
But it also have that advert effect of breaking the style of the entities in the 'stack-in-card' and the cards that has styling on it.

**Comment by bymem** [comment]
I tip my hat at you.

that did the trick and work, thank you so much.

**Comment by skynet01** [comment]
> Try smth like this:
> 
> ```
> card-mod-card: |
>     ha-card {
>       {% if config.entity is defined %}
>         {% if config.entity.startswith('light.') and is_state(config.entity, 'on') %}
>           background-color: red;
>         {% endif %}
>       {% endif %}
>     }
> ```
Hmm this stopped working since the recent update. Any ideas on how to fix? Getting this error now:

```
Logger: homeassistant.helpers.event
Source: helpers/template.py:570
First occurred: 1:59:59 PM (188 occurrences)
Last logged: 2:00:13 PM

Error while processing template: Template<template=(@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if states(config.entity.startswith('fan.')) and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }) renders=134>
Error while processing template: Template<template=(@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if states(config.entity.startswith('fan.')) and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }) renders=136>
Error while processing template: Template<template=(@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if states(config.entity.startswith('fan.')) and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }) renders=138>
Error while processing template: Template<template=(@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if states(config.entity.startswith('fan.')) and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }) renders=140>
Error while processing template: Template<template=(@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(359deg); } } state-badge { {% if states(config.entity.startswith('fan.')) and is_state(config.entity, 'on') %} animation: spin 4s infinite linear; {% endif %} }) renders=142>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 3, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 871, in __call__
    state = _get_state(self._hass, entity_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1127, in _get_state
    return _get_template_state_from_state(hass, entity_id, hass.states.get(entity_id))
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1500, in get
    return self._states.get(entity_id.lower())
                            ^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: AttributeError: 'bool' object has no attribute 'lower'
```
