### ISSUE TITLE
Glance card w/o card-mod opened in UI Editor: errors in Code Inspector

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-card-mod#348]
My Home Assistant version: 2024.1.1

My lovelace configuration method (GUI or yaml): storage

What I am doing:
Creating a Glance card w/o card-mod in UI Editor.

What I expected to happen:
No errors in Code Inspector & UI Editor.

What happened instead:
1. Errors are shown in UI Editor (seems to be unrelated to card-mod & may be reproduced on a system w/o card mod - see https://github.com/home-assistant/frontend/issues/19325):

Visual editor is not supported for this configuration:
Key 'entities.0.show_state' is not expected or not supported by the visual editor.
The provided value for 'entities.0' is not supported by the visual editor. We support (string) but received ({"entity":"sun.sun","name":"Front 1","show_state":false}).
Key 'entities.1.show_state' is not expected or not supported by the visual editor.
The provided value for 'entities.1' is not supported by the visual editor. We support (string) but received ({"entity":"sun.sun","name":"Front 2","show_state":false}).
Key 'entities.2.show_state' is not expected or not supported by the visual editor.
The provided value for 'entities.2' is not supported by the visual editor. We support (string) but received ({"entity":"sun.sun","name":"Front 3","show_state":false}).
You can still edit your config in YAML.

2. Errors are shown in Code Inspector:

Card-mod r: At path: entities.0 -- Expected the value to satisfy a union of `object | string`, but received: [object Object]
    at d (http://192.168.220.32:8123/frontend_latest/38768.-gCP239u5SQ.js:1:2807)
    at f (http://192.168.220.32:8123/frontend_latest/38768.-gCP239u5SQ.js:1:2615)
    at F.value (http://192.168.220.32:8123/frontend_latest/20207.KXnjAt08q54.js:2:13710)
    at F.value (http://192.168.220.32:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:59842)
    at F.i (http://192.168.220.32:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:52936)
    at t.setConfig (http://192.168.220.32:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244:215:1564)
    at F.i [as setConfig] (http://192.168.220.32:8123/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524341:1:53062)
    at F.value (http://192.168.220.32:8123/frontend_latest/21948.wVYWKAjUy9c.js:1:15379)
    at F.value (http://192.168.220.32:8123/frontend_latest/21948.wVYWKAjUy9c.js:1:11120)
    at F.value (http://192.168.220.32:8123/frontend_latest/21948.wVYWKAjUy9c.js:1:10811)

With no UI Editor open after browser's refresh (F5) - no errors:

![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/c79f3ad5-e1c0-4d3d-8c6a-e346795a07ac)

With UI Editor open:
![image](https://github.com/thomasloven/lovelace-card-mod/assets/71872483/7b330083-e74e-42cd-b94b-7b2eb9446fac)

**Minimal** steps to reproduce:

```
type: glance
entities:
  - entity: sun.sun
    name: Front 1
    show_state: false
  - entity: sun.sun
    name: Front 2
    show_state: false
  - entity: sun.sun
    name: Front 3
    show_state: false
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Still in 3.4.5, 2025.10.1:

<img width="1759" height="935" alt="Image" src="https://github.com/user-attachments/assets/8e6169e4-2335-4482-bf0d-d4d72a12d2cb" />

A similar issue created in frontend repo (https://github.com/home-assistant/frontend/issues/19325, was not sure if this is a card-mod-related glitch) was closed as stale.

**Comment by dcapslock** [comment]
console errors are generated in [patch function](https://github.com/thomasloven/lovelace-card-mod/blob/b0ac00c05e2bc21dca029e3e13d28845b6e02dfd/src/helpers/patch_function.ts#L10) when the patched function throws an error. In this case it is setConfig for the card which raises structError which will be caught in Frontend and not raise errors.

@thomasloven any reason this conole.error() call is needed? Can we remove altogther or prhaps don't log for expected errors like structError?

**Comment by thomasloven** [comment]
That's probably a debug message left by mistake.

**Comment by dcapslock** [comment]
[v4.0.0-beta.2](https://github.com/thomasloven/lovelace-card-mod/releases/tag/v4.0.0-beta.2) available for testing.

**Comment by dcapslock** [comment]
[v4.0.0](https://github.com/thomasloven/lovelace-card-mod/releases/tag/v4.0.0) released

**Comment by ildar170975** [comment]
2025.11.3, card-mod 4.0.0.
`extra_module_url` contains a line (same tag as on a screenshot & in resources):
```
/hacsfiles/lovelace-card-mod/card-mod.js?hacstag=190927524400
```
See errors in Editor, but not in console:

<img width="1745" height="695" alt="Image" src="https://github.com/user-attachments/assets/e1cf6fdc-23ec-4fcc-8bb0-3df76d96d66d" />

Same w/o card-mod installed.
So, have no idea if it is related to card-mod.

**Comment by dcapslock** [comment]
Not card_mod. See [comment](https://github.com/home-assistant/frontend/issues/19325#issuecomment-1881404630) in the linked Frontend issue.

**Comment by ildar170975** [comment]
Agree, seems to be so.
